local:
  app:
    name: "go-cli-ddd"
    debug: true
    log_level: "debug"

  database:
    dialect: "mysql"
    dsn: "file:go-cli-ddd.db?cache=shared"
    log_level: "info"
    auto_migrate: true
    secret_id: ""
    aurora:
      enabled: false
      writer:
        secret_id: ""
      reader:
        secret_id: ""
        load_balancing: "random"

  http:
    timeout: 30
    max_retries: 3
    rate_limit:
      qps: 10.0
      burst: 3

  external_api1:
    base_url: "http://localhost:8080"
    token_secret_id: ""

  external_api2:
    base_url: "https://api.example.com"
    token_secret_id: "prd/api/token"

  notification:
    slack:
      enabled: true
      webhook_url: "https://hooks.slack.com/services/your-webhook-url"
      channel: "#notifications"
      username: "CLI Bot"
      icon_emoji: ":robot_face:"
      success_emoji: ":white_check_mark:"
      failure_emoji: ":x:"

  aws:
    region: "ap-northeast-1"
    secrets:
      enabled: false

dev:
  app:
    debug: true
    log_level: "info"

  database:
    dialect: "mysql"
    dsn: "file:go-cli-ddd-dev.db?cache=shared"
    secret_id: "dev/database/go-cli-ddd"
    aurora:
      enabled: true
      writer:
        secret_id: "dev/database/aurora-writer"
      reader:
        secret_id: "dev/database/aurora-reader"
        load_balancing: "round-robin"

  external_api1:
    base_url: "https://dev-api.example.com"
    token_secret_id: "dev/api/token"

  external_api2:
    base_url: "https://dev-api.example.com"
    token_secret_id: "prd/api/token"

  notification:
    slack:
      enabled: true
      webhook_url: "https://hooks.slack.com/services/your-dev-webhook-url"
      webhook_secret_id: "dev/slack/webhook"
      channel: "#dev-notifications"
      username: "CLI Bot (Dev)"
      icon_emoji: ":robot_face:"
      success_emoji: ":white_check_mark:"
      failure_emoji: ":x:"

  aws:
    region: "ap-northeast-1"
    secrets:
      enabled: true

prd:
  app:
    debug: false
    log_level: "info"

  database:
    dialect: "mysql"
    dsn: "file:go-cli-ddd-prd.db?cache=shared"
    log_level: "error"
    secret_id: "prd/database/go-cli-ddd"
    aurora:
      enabled: true
      writer:
        secret_id: "prd/database/aurora-writer"
      reader:
        secret_id: "prd/database/aurora-reader"
        load_balancing: "round-robin"

  external_api1:
    base_url: "https://api.example.com"
    token_secret_id: "prd/api/token"

  external_api2:
    base_url: "https://api.example.com"
    token_secret_id: "prd/api/token"

  notification:
    slack:
      enabled: true
      webhook_url: ""
      webhook_secret_id: "prd/slack/webhook"
      channel: "#prd-notifications"
      username: "CLI Bot (Prd)"
      icon_emoji: ":robot_face:"
      success_emoji: ":white_check_mark:"
      failure_emoji: ":x:"

  aws:
    region: "ap-northeast-1"
    secrets:
      enabled: true
